# Generated by Django 5.1.3 on 2025-02-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=0, verbose_name='产品状态')),
                ('encode', models.CharField(max_length=20, verbose_name='产品编码')),
                ('name', models.CharField(max_length=20, verbose_name='产品名称')),
                ('category', models.CharField(max_length=20, verbose_name='产品品类')),
                ('node', models.CharField(max_length=20, verbose_name='节点类型')),
                ('type', models.CharField(max_length=20, verbose_name='产品类型')),
                ('car', models.CharField(max_length=20, verbose_name='接入车系')),
                ('num', models.IntegerField(max_length=20, verbose_name='接入设备数量')),
            ],
        ),
    ]
